### ISSUE TITLE
build error in mdns-module

### ISSUE THREAD

**Issue by dasarne** [volumio/Volumio2#50] opened 2015-09-01 18:50 UTC
Compiling Volumio 2 from Git-Clone (01.09.2015) dies in compiling mdns, because dns_sd.h is missing:

```bash
> mdns@2.2.9 install /volumio/node_modules/mdns
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory '/volumio/node_modules/mdns/build'
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
In file included from ../src/dns_sd.cpp:1:0:
../src/mdns.hpp:32:20: fatal error: dns_sd.h: No such file or directory
 #include <dns_sd.h>
                    ^
compilation terminated.
dns_sd_bindings.target.mk:133: recipe for target 'Release/obj.target/dns_sd_bindings/src/dns_sd.o' failed
make: *** [Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
make: Leaving directory '/volumio/node_modules/mdns/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.16.0-4-686-pae
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /volumio/node_modules/mdns
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 

```
npm-debug.log can be found here
https://jim.itmc.tu-dortmund.de/oc/index.php/s/VclhXbh8PHRit9d/download

**Comment by jomo** [comment] 2015-09-01 19:19
This is a duplicate of #34.

**Closed by jomo** 2015-09-01 19:19 UTC
Labels: duplicate
