### ISSUE TITLE
DSD over PCM option is missing

### ISSUE THREAD

**Issue by codewarriorFX** [volumio/Volumio2#455] opened 2016-06-06 01:37 UTC
If I use HDMI to my A/V receiver, I need DoP. Most A/V receiver's DAC does not support native DSD.

Tested it on my Yamaha receiver is a RX-A800, an Aventage model and it has a Burr Brown DAC that can go up to 24-bit / 192kHz (PCM only).

**Comment by xipmix** [comment] 2016-11-28 12:08
Duplicate of #267? 

I think this feature has gone [in](https://github.com/volumio/Volumio2/commit/b73ecb8be6f1e0ef12cbfba66a393bd9e621ee3d), please test 2.031 or later.

**Closed** 2017-06-02 22:58 UTC
Labels: Feedback
