### ISSUE TITLE
Volumio doesn't recognize wifi channel 13 (for Europe)

### ISSUE THREAD

**Issue by ant-ds** [volumio/Volumio2#2022] opened 2020-11-24 10:08 UTC
Volumio is not able to connect to/detect my WIFI when it broadcasts on 2.4ghz channel 13. This is due to the fact that this channel is "illegal" in America. However this channel can freely be used in Europe.
Could this channel be supported by default depending on the region?

**Comment by ashthespy** [comment] 2020-11-24 11:24
Dupe of https://github.com/volumio/Volumio2/issues/1985 ?

**Closed** 2020-11-27 15:09 UTC
