### ISSUE TITLE
Volumio will not play Spotify playlist

### ISSUE THREAD

**Issue by dai-kan** [volumio/Volumio2#1730] opened 2019-03-01 17:28 UTC
With Volumio ver 2.555 installed, Spotify ver 1.35, Modified index.js file with Spotify refresh token per directions in member2398.html, afterwards Spotify playlist is visible in Browse-Spotify-My Playlist-Playlist1. Playlist1 was created in Spotify. The problem now is when I click on the item to play, nothing happens. Likewise the using play in right hand drop down box does not work either. Please help.

**Comment by wibenjamin** [comment] 2019-03-03 12:44
I can confirm this problem too. I tried the latest Volumio Release and also V2.411 and V2.389 also with the modiefied index.js file.  Access and authentification via the refresh token seems to work, playback of single tracks from spotify search is working, also tracks and playlists from the "Whats new" tab also appear to work. All the other playlists are showing fine but they can not be accessed or played or added to the queue.

**Comment by daveschafer** [comment] 2019-03-13 13:53
I can also confirm, that this issue still persists in Version 2.565

**Comment by Csierra099** [comment] 2019-03-15 17:57
Indeed the problem still persits, is there any solution out there or maybe an alternative? I'm the IT guy from an hotel and we have 3 Pi's running Volumio but since this problem started going on we've been having a lot of issues trying to put music.

**Comment by Baudouin0** [comment] 2019-04-07 17:28
Any plan to fix this?

**Comment by dai-kan** [comment] 2019-04-07 18:54
I posted this as an issue.  Perhaps someone from Volumio can pick it up and find a solution.

**Comment by wibenjamin** [comment] 2019-04-08 19:00
The developer of the plugin fixed the issue and it is working fine for me.

Check this thread and just follow his instructions:
[https://forum.volumio.org/spotify-playlists-not-working-anymore-t11918.html#p61273](url)

**Comment by xipmix** [comment] 2019-04-09 11:28
If this is really fixed, can you please close this issue?

**Comment by Baudouin0** [comment] 2019-04-09 18:10
Did clone the latest git branch and installed manually into volumio. Still cannot get any sound from genres and modes, the only thing which plays are the new releases.

**Closed** 2019-04-09 19:35 UTC

**Comment by b-d-k** [comment] 2019-05-29 02:18
This has unfortunately not been fixed. There is a somewhat 'hacky' fix in this fork: https://github.com/skikirkwood/volumio-plugins, but the changes are not in this repo, nor could I find a PR for it.

**Comment by koesper** [comment] 2019-12-30 13:47
are there any updates on this? still doesnt work with the 'official' versions, right?

**Comment by volumio** [comment] 2019-12-30 13:55
Yes we fixed it. Update volumio to latest version and update spotify to latest version. Then authorise it
