### ISSUE TITLE
v0.976 Playback options problems

### ISSUE THREAD

**Issue by chsims1** [volumio/Volumio2#600] opened 2016-07-29 09:18 UTC
Updated to v0.976 on RPi Zero, and there seems to a problem on the Playback options:

![screen](https://cloud.githubusercontent.com/assets/6384195/17243628/b79ac03a-5575-11e6-8bc0-f77f31809ca1.png)

**Comment by paviro** [comment] 2016-07-29 11:09
Same on Pi 2 :)

**Comment by xipmix** [comment] 2016-11-29 10:19
Is this still a problem for you with 2.031? I have seen this on a pi2 with that version and it went away when I clicked on the selector next to the 'value not found' message. I recall it appeared after I changed the Mixer Type from hardware to none, but I can't reproduce it now.

**Comment by macmpi** [comment] 2016-11-29 12:04
Looks duplicate of [this](https://github.com/volumio/Volumio2-UI/issues/207): was fixed since (fresh) 2.01.

**Comment by chsims1** [comment] 2016-11-29 12:08
Not a problem anymore  for me on Pi0, Pi2 or Pi3.

**Closed** 2017-06-02 23:02 UTC
Labels: Bug
