### ISSUE TITLE
Volume Control

### ISSUE THREAD

**Issue by clemensmartin** [volumio/Volumio2#492] opened 2016-06-28 16:09 UTC
RC2: 
The user interface does not show any text in the Volume Control Mixer Option field on a 
RPI with HifiBerry DAC (no plus). 
The drop down menu does not contain any entries in this case. 
Also (brought up in the discussion forum) the output device field continues to show "Audio Jack"
although sound is played through the DACs RCA connectors.

**Comment by apinner** [comment] 2016-06-28 16:11
Duplicate of https://github.com/volumio/Volumio2/issues/485

**Closed by apinner** 2016-06-28 16:11 UTC
